# Generated by Django 5.2.5 on 2025-09-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
