# Generated by Django 5.2.5 on 2025-09-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_product_is_available_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='on_sale',
        ),
    ]
