# Generated by Django 5.2.5 on 2025-09-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_rename_is_sale_product_on_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
