# Generated by Django 5.2.5 on 2025-09-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_rename_location_profile_city_profile_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
