# Generated by Django 5.2.5 on 2025-09-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_profile_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
